name: Build Executables

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    
    - name: Install PyInstaller
      run: pip install pyinstaller
    
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed src/gui_app.py
        mv dist/gui_app dist/PhantomVault-${{ runner.os }}
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: PhantomVault-${{ runner.os }}
        path: dist/
