name: Python CI with Conda

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]  # Test multiple Python versions

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        activate-environment: phantomvault
        auto-update-conda: true
        channels: conda-forge,defaults

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg  # Required for pydub

    - name: Install Python dependencies
      shell: bash -l {0}  # Important for Conda environments
      run: |
        conda install -n phantomvault -c conda-forge --file requirements.txt || true
        conda install -n phantomvault -c conda-forge pytest pytest-cov
        pip install -r requirements.txt
        pip install -e .

    - name: Run tests
      shell: bash -l {0}
      run: |
        pytest tests/ -v --cov=src --cov-report=xml

    - name: Upload coverage
      uses: codecov/codecov-action@v3
